spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: db/migration/postgres
server:
  http2:
    enabled: true
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: DW!1je81$gESIh*zgRMg$8^nMVdKUvEG
    key-store-type: PKCS12
    key-alias: raceconditiondemo
  port: 8443
