CREATE TABLE TEACHERS
(
    ID   UUID DEFAULT random_uuid() PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL
);

CREATE TABLE USERS
(
    ID   UUID DEFAULT random_uuid() PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL
);

CREATE TABLE RANKINGS
(
    ID          UUID DEFAULT random_uuid() PRIMARY KEY,
    REVIEWER_ID UUID      NOT NULL,
    TEACHER_ID  UUID      NOT NULL,
    SCORE       SMALLINT  NOT NULL,
    COMMENT     VARCHAR(4096),
    DATE_ADDED  TIMESTAMP NOT NULL,
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (id),
    FOREIGN KEY (REVIEWER_ID) REFERENCES USERS (id)
);
